### ISSUE TITLE
[EPIC] Have A2 architecture working

### ISSUE THREAD

**Issue by felipe-clark** [Urmi20/CloudComputing#33]
A2's architecture is as follows:

- [ ] A fixed EC2 instance for the management UI. This instance must save the management settings (scale and shrink factors and CPU usage etc.) to the database;

- [ ] A fixed EC2 instance for the scaling application. This is a dedicated Python application that monitors the loads in the EC2 instances and starts or terminates instances based on load. This application's  pool rate must be properly calculated to avoid avalanches of spawned and terminated instances. A pool rate of 5 minutes should suffice as a start point from which we can optimize later.

- [ ] A fixed EC2 instance running the database. The database must be accessible by the user UI, manager UI and the scaling application. A new table will have to be created to hold the scaling settings;

- [ ] A minimum of one EC2 instance to run the user UI. Once this instance is in a releasable state (e.g.: saving to and loading images from S3) we shall create an AMI from this instance to be used as a reference for the scaling group;

- [ ] Configure a load balancer to assign clients to our instances.
